Update vuln_scanner.yaml

diff --git a/.github/workflows/vuln_scanner.yaml b/.github/workflows/vuln_scanner.yaml
--- a/.github/workflows/vuln_scanner.yaml
+++ b/.github/workflows/vuln_scanner.yaml
@@ -63,11 +63,11 @@ jobs:
         working-directory: ./jit
         run: ./gradlew spotbugsMain
 
-      # - name: Run OWASP Dependency-Check
-      #   working-directory: ./jit
-      #   run: |
-      #     ./gradlew dependencyCheckAnalyze -Ddependency-check.cache-dir=./cache --info
-      #     ls -R ./jit/build || echo "Build directory not found."
+      - name: Run OWASP Dependency-Check
+        working-directory: ./jit
+        run: |
+          ./gradlew dependencyCheckAnalyze -Ddependency-check.cache-dir=./cache --info
+          ls -R ./jit/build || echo "Build directory not found."
     
       - name: Debug file structure (Check for application.properties)
         run: |
